async function api(url,options={}){const r=await fetch(url,{credentials:"include",...options});const d=await r.json().catch(()=>({}));if(!r.ok)throw Error(d.error||"İşlem başarısız");return d}
const $=s=>document.querySelector(s); const esc=s=>String(s??"").replace(/[&<>"']/g,m=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[m]));
document.querySelectorAll(".nav").forEach(b=>b.onclick=()=>showPage(b.dataset.page));
function showPage(id){document.querySelectorAll(".page").forEach(x=>x.classList.remove("active"));$("#"+id).classList.add("active");document.querySelectorAll(".nav").forEach(x=>x.classList.toggle("active",x.dataset.page===id));$("#pageTitle").textContent=document.querySelector(`.nav[data-page="${id}"]`).textContent.trim();loadPage(id)}
async function loadPage(id){try{if(id==="dashboard")loadStats();if(id==="users")loadUsers();if(id==="films")loadFilms();if(id==="upload")loadCategories();if(id==="categories")loadCategoriesList();if(id==="payments"){loadPayments();loadShopier()}if(id==="messages")loadMessages();if(id==="settings")loadSettings()}catch(e){alert(e.message)}}
async function loadStats(){const s=await api("/api/admin/stats");$("#stats").innerHTML=Object.entries(s).map(([k,v])=>`<div class="stat">${esc(k)}<strong>${v}</strong></div>`).join("")}
async function loadUsers(){const u=await api("/api/admin/users");$("#usersTable").innerHTML=`<div class="table"><div class="row head"><span>Ad</span><span>E-posta</span><span>Rol</span><span>Durum</span><span></span></div>${u.map(x=>`<div class="row"><span>${esc(x.name)}</span><span>${esc(x.email)}</span><span>${esc(x.role)}</span><span>${x.active?"Aktif":"Pasif"}</span><span><button class="mini" onclick="toggleUser('${x.id}',${!x.active})">${x.active?"Pasifleştir":"Aktifleştir"}</button></span></div>`).join("")}</div>`}
async function toggleUser(id,active){await api("/api/admin/users/"+id,{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify({active})});loadUsers()}
async function loadFilms(){const f=await api("/api/films");$("#filmsTable").innerHTML=`<div class="table"><div class="row head"><span>Film</span><span>Kategori</span><span>Yıl</span><span>Video</span><span></span></div>${f.map(x=>`<div class="row"><span>${esc(x.title)}</span><span>${esc(x.categoryId)}</span><span>${esc(x.year)}</span><span>${x.videoUrl?"MP4 hazır":"Yok"}</span><span><button class="mini del" onclick="deleteFilm('${x.id}')">Sil</button></span></div>`).join("")}</div>`}
async function deleteFilm(id){if(!confirm("Film silinsin mi?"))return;await api("/api/admin/films/"+id,{method:"DELETE"});loadFilms()}
async function loadCategories(){const c=await api("/api/categories");$("#categorySelect").innerHTML='<option value="">Kategori seç</option>'+c.map(x=>`<option value="${x.id}">${esc(x.name)}</option>`).join("")}
async function loadCategoriesList(){const c=await api("/api/categories");$("#catList").innerHTML=c.map(x=>`<div class="row"><span>${esc(x.name)}</span><span></span><span></span><span></span><button class="mini del" onclick="deleteCat('${x.id}')">Sil</button></div>`).join("")}
async function deleteCat(id){await api("/api/admin/categories/"+id,{method:"DELETE"});loadCategoriesList()}
$("#catForm").onsubmit=async e=>{e.preventDefault();const f=new FormData(e.target);await api("/api/admin/categories",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({name:f.get("name")})});e.target.reset();loadCategoriesList();loadCategories()}
$("#filmForm").onsubmit=async e=>{e.preventDefault();$("#uploadMsg").textContent="Yükleniyor...";try{const r=await fetch("/api/admin/films",{method:"POST",credentials:"include",body:new FormData(e.target)});const d=await r.json();if(!r.ok)throw Error(d.error);$("#uploadMsg").textContent="Film başarıyla yüklendi.";e.target.reset()}catch(x){$("#uploadMsg").textContent=x.message}}
async function loadPayments(){const p=await api("/api/admin/payments");$("#paymentStats").textContent=`Toplam kayıt: ${p.length}`;$("#paymentsTable").innerHTML=p.map(x=>`<div class="row"><span>${esc(x.provider)}</span><span>${esc(x.status)}</span><span>${esc(x.receivedAt)}</span><span></span><span></span></div>`).join("")}
async function loadShopier(){const c=await api("/api/payments/shopier/config");$("#webhookUrl").textContent=c.webhookUrl;$("#successUrl").textContent=c.successUrl;$("#failureUrl").textContent=c.failureUrl;const s=await api("/api/admin/settings");const f=$("#shopierForm");f.enabled.checked=s.shopier.enabled;f.merchantId.value=s.shopier.merchantId||""}
$("#shopierForm").onsubmit=async e=>{e.preventDefault();const f=new FormData(e.target);await api("/api/admin/settings",{method:"PUT",headers:{"Content-Type":"application/json"},body:JSON.stringify({shopier:{enabled:f.get("enabled")==="on",merchantId:f.get("merchantId"),apiKey:f.get("apiKey"),apiSecret:f.get("apiSecret")}})});$("#shopierMsg").textContent="Shopier ayarları kaydedildi."}
async function loadMessages(){const m=await api("/api/admin/messages");$("#messagesTable").innerHTML=m.map(x=>`<div class="row"><span>${esc(x.userId)}</span><span>${esc(x.text)}</span><span>${esc(x.status)}</span><span>${esc(x.createdAt)}</span><span></span></div>`).join("")}
async function loadSettings(){const s=await api("/api/admin/settings");const f=$("#settingsForm");f.siteName.value=s.siteName;f.monthlyPrice.value=s.monthlyPrice;f.currency.value=s.currency}
$("#settingsForm").onsubmit=async e=>{e.preventDefault();const f=new FormData(e.target);await api("/api/admin/settings",{method:"PUT",headers:{"Content-Type":"application/json"},body:JSON.stringify({siteName:f.get("siteName"),monthlyPrice:Number(f.get("monthlyPrice")),currency:f.get("currency")})});$("#settingsMsg").textContent="Ayarlar kaydedildi."}
$("#logout").onclick=async()=>{await api("/api/auth/logout",{method:"POST"});location.href="/"}
(async()=>{try{const m=await api("/api/auth/me");if(m.user.role!=="admin")throw Error("Admin hesabıyla giriş yapmalısınız.");loadStats()}catch(e){alert(e.message);location.href="/#login"}})();